name: Build and Tag for Hotfix Branches

# Trigger the workflow when PRs are created or updated from branches with the hotfix prefix
on:
  pull_request:
    branches:
      - 'hotfix/**'

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up any language-specific dependencies (e.g., Node.js, Python, etc.)
      - name: Set up Node.js (example step for Node.js project)
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Install dependencies and build the project
      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Determine the new version based on the commit hash (short version)
      - name: Get short commit hash
        id: short_commit_hash
        run: |
          short_commit=$(git rev-parse --short HEAD)
          echo "short_commit=$short_commit" >> $GITHUB_ENV

      - name: Create Git tag with commit hash
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@users.noreply.github.com"
          git tag hotfix-${{ env.short_commit }} -m "Release version based on hotfix commit ${{ env.short_commit }}"
          git push origin hotfix-${{ env.short_commit }}

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.short_commit }}
          release_name: "Release hotfix-${{ env.short_commit }}"
          draft: false
          prerelease: false